### ISSUE TITLE
No "Save" option.

### ISSUE THREAD

**Issue by MartinFlischman** [calo001/fondo#100]
1) There is no option to save the photo/s to my laptop. I would like to save it and then set it myself.

2) I don't think the Fondo app should set the wallpaper automatically when you click on an image. It should give the user the option to download or set it manually.

**Comment by xgqt** [comment]
Bump.
Fondo doesn't work with my desktop (XFCE). 
I'd like to save the wallpapers and then set them via my desktop's settings.

**Comment by calo001** [comment]
@MartinFlischman 
1. An option to download the wallpaper is now available in the 1.5.0 version! :D Enjoy! 
2. Traditionally Fondo started with that functionality but in a future version I'm planning to add settings witch will cover this behavior.
@xgqt If the error persists, could you create a new issue?
