### ISSUE TITLE
(Now, on KDE) Error copy from URI to directory

### ISSUE THREAD

**Issue by guilmour-asc** [calo001/fondo#105]
Hello. **Congrats and thanks for this app, I love it and use it frequently**.
But I need to address the image error issue, once fixed for GNOME environments, now also on KDE, and I'd like to know if there's a workaround...

### My specs:
**Operating System:** Kubuntu 20.04
**KDE Plasma Version:** 5.18.5
**KDE Frameworks Version:** 5.68.0
**Qt Version:** 5.12.8
**Kernel Version:** 5.4.0-40-generic
**OS Type:** 64-bit
**Processors:** 4 × Intel® Core™ i7-5500U CPU @ 2.40GHz
**Memory:** 7,7 GiB

### Screencap
![Screenshot_20200707_205223](https://user-images.githubusercontent.com/26415345/86857538-1ac50100-c095-11ea-86b8-95792f6ee40c.png)

**Comment by IsraPerez98** [comment]
Same issue here, using KDE on Arch Linux

**Comment by kuznero** [comment]
Same issue on Elementary

**Comment by calo001** [comment]
@kuznero Hi! could you tell me what fondo version are you using? and if is the Flatpak o Appcenter version? Please :)

**Comment by kuznero** [comment]
@calo001 I just `sudo apt install com.github.calo001.fondo` - I guess this is equivalent to installing from the AppCenter. But interestingly it is not working only on one of my laptops. Both run Elementary, both got it installed exactly same way.

**Comment by prandot** [comment]
Hola @calo001 , 
Felicitaciones por la aplicación. Me gustaría saber si fue hecho solo para gnome o también funciona para KDE?
Tengo el mismo problema de @guilmour-asc 
Muchas gracias
![Screenshot_20201120_085512](https://user-images.githubusercontent.com/74741428/99774657-64772b00-2b0e-11eb-8950-1fb2d3510fbc.png)

**Comment by calo001** [comment]
@prandot Hola amigo, muchas gracias, lamentablemente Fondo esta solo disponible para entornos Gnome o derivados, siendo mi objetivo principal la distro de elementary OS.

**Comment by calo001** [comment]
@guilmour-asc @IsraPerez98 Hi, unfortunately, Fondo only works on GNOME environments

**Comment by guilmour-asc** [comment]
Hello, @calo001. Thanks for the attention, and also, I understand the scenario. No problems for me, by the way, I'm on wait for the new elementary 6 to come, so it won't be a problem for me, after all. :)

**Comment by guilmour-asc** [comment]
@kuznero, sorry for closing, by knowing you have an issue involving use of this app on elementary OS itself...
As I made this issue exclusively for the KDE scenario, this specific issue ended its purpose.
