### ISSUE TITLE
Option to only view landscape or portrait pictures

### ISSUE THREAD

**Issue by arshubham** [calo001/fondo#12]

**Comment by calo001** [comment]
In version 1.1.3 now the photos are ordered from portrait to landscape, I'm limited for the moment to show them that way, because the unsplash API does not allow me to obtain them from just one of the two options (portait or landscape)

**Comment by arshubham** [comment]
@calo001 You can do a simple check if width>hight then landscape and if reverse then portrait and filter the images shown

**Comment by calo001** [comment]
I need to make some designs, I need to consider that each request is of maximum 30 photos that combine an indefinite number in landscape and portrait, so if the filter is activated, I do not know how the UI behaves when navigating, but I will do some tests, it would be an amazing feature.

**Comment by arshubham** [comment]
I am not taking about the request. Just that when all the 30 images are loaded give a mode switch to show landscape only and hide the portrait images

**Comment by cassidyjames** [comment]
Some portrait wallpapers are high resolution enough and composed so they work well when cropped to landscape, so I can see some value in being able to browse them as well. Or if the user has a rotatable display and wants to set something that will look great when they're in portrait mode. But I agree defaulting to the current orientation would be smart!

**Comment by matfantinel** [comment]
Hasn't this been published already? I think this issue can be closed.

Great job!
