### ISSUE TITLE
Update OARS data

### ISSUE THREAD

**Issue by cassidyjames** [calo001/fondo#13]
Since your app hits an online API, its `social-info` content attribute should be set to mild or higher:

```xml
<content_attribute id="social-info">mild</content_attribute>
```

If more diagnostic data is shared (i.e. more than a ping), it should be moderate or higher:

```xml
<content_attribute id="social-info">moderate</content_attribute>
```

If potentially user-identifiable data (like logs or usernames) are shared, it should be intense:

```xml
<content_attribute id="social-info">intense</content_attribute>
```

**Comment by calo001** [comment]
I have a doubt, for the "intense" value includes the fact of showing the user name shown below each photo? or is it only in case of handling information from the elementary os user account?

So I understand the API Unsplash only register the total number of request,views and downloads that are made, It would then only "moderate"?

**Comment by cassidyjames** [comment]
@calo001 This applies to sharing information from the user of your app to a third party (yourself or anyone else). I think in the case of the Unsplash API, it would just be `mild`. You're not collecting or sending any other diagnostic data other than hitting the API itself.
