### ISSUE TITLE
Serbian translation

### ISSUE THREAD

**Issue by youngLights14** [calo001/fondo#136]
I have modified Croatian translation to Serbian (they were once one language, they have some small differences), but I don't know how to submit the file.

Thanks everyone for great app.

**Comment by vfrico** [comment]
You should make a fork of the repository (top right button on this page) and then make all the changes you want to do in that repository: its yours, so you will have upload and edit permissions. Then, open a pull request to this repository (when you make changes, Github recommends to do so).

Thanks to you for contributing!
