### ISSUE TITLE
doesnt change wallpaper on popos

### ISSUE THREAD

**Issue by MustaphaAlioglou** [calo001/fondo#139]

**Comment by MustaphaAlioglou** [comment]
i reinstalled popos to test it and it didnt work even after a clean install. the bar doesnt show that its downloading the image and it doesnt change even after i gave it a couple of minutes

**Comment by MustaphaAlioglou** [comment]
Gtk-Message: 17:24:09.287: Failed to load module "appmenu-gtk-module"

(com.github.calo001.fondo:2): Json-CRITICAL **: 17:24:11.980: json_object_get_string_member: assertion 'node != NULL' failed

** (com.github.calo001.fondo:2): CRITICAL **: 17:24:11.980: app_utils_wallpaper_construct: assertion 'uri_endpoint != NULL' failed

(com.github.calo001.fondo:2): GLib-GObject-WARNING **: 17:24:11.981: invalid (NULL) pointer instance

(com.github.calo001.fondo:2): GLib-GObject-CRITICAL **: 17:24:11.981: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(com.github.calo001.fondo:2): GLib-GObject-WARNING **: 17:24:11.981: invalid (NULL) pointer instance

(com.github.calo001.fondo:2): GLib-GObject-CRITICAL **: 17:24:11.981: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (com.github.calo001.fondo:2): CRITICAL **: 17:24:11.981: app_utils_wallpaper_update_wallpaper: assertion 'self != NULL' failed

**Comment by calo001** [comment]
Please check issue #140 :+1:
