### ISSUE TITLE
Images not downloading

### ISSUE THREAD

**Issue by wsamh** [calo001/fondo#140]
when I select an image the progress bar just hangs and nothing happens.
![Screenshot from 2021-03-10 10-30-37](https://user-images.githubusercontent.com/67978594/110679033-db9f0080-818b-11eb-9c5e-71ea5ccce5a5.png)

**Comment by eliezer-v** [comment]
same problem here under fedora core latest and ubuntu 20.04

**Comment by cesar2m** [comment]
In Fedora 33 (Kernel: 5.10.21-200.fc33.x86_64) I'm same problem.

**Comment by GustavoSantosCS** [comment]
Same problem using ubuntu 20.04. Have any solution?

![image](https://user-images.githubusercontent.com/26032696/110834393-3e6fc500-827c-11eb-96f1-6e411e8fca20.png)

**Comment by Colbiedelvale** [comment]
I am having the same problem on Zorin OS 15.3, a week ago it worked normally.

**Comment by calo001** [comment]
Hi! I'm currently working on a fix for this issue, please stay tuned. The Unsplash API provides a download endpoint, but it returns an OAuth error, which I think is a bug from the API.

**Comment by calo001** [comment]
Issue solved in version 1.5.2 :smile:
