### ISSUE TITLE
Progress bar doesn't hide when setting a wallpaper is complete

### ISSUE THREAD

**Issue by cassidyjames** [calo001/fondo#164]
Minor visual issue I noticed. After setting a wallpaper, the progress bar stays visible.

![Screenshot from 2021-08-18 13-50-16@2x](https://user-images.githubusercontent.com/611168/129962862-40437b1b-cbc0-44dc-9eb6-1c77a9da1718.png)

**Comment by calo001** [comment]
Thanks, you're right! I just worked on it, now it's available on version 1.6.1, the progress bar hides when the download finishes.
