### ISSUE TITLE
A hard coded (non-translatable) string

### ISSUE THREAD

**Issue by ma-ta** [calo001/fondo#167]
In [fondo/src/Views/DarkModeOption.vala](https://github.com/calo001/fondo/blob/c2465ce1bc335833fece78390e8d70a630ea4e75/src/Views/DarkModeOption.vala) currently on the row 122 there is a non-translated string "Estilo" in the code:
`var lbl_mode_optios = new Gtk.Label ("Estilo");`

Probably it is needed to add the string to the file [fondo/src/Configs/Strings.vala](https://github.com/calo001/fondo/blob/c2465ce1bc335833fece78390e8d70a630ea4e75/src/Configs/Strings.vala) and generate a new POT template?

**Comment by calo001** [comment]
Thanks! You are right, I just fixed it in the last commit, do you mind if I asked you if you can update your PR for the STYLE_HEADER_LABEL string in the fondo/src/Configs/Strings.vala file?

**Comment by ma-ta** [comment]
Hi, there are currently two pull requests for Czech translation. I have translated all the new strings including the STYLE_HEADER_LABEL:
- Update cs.po #169
- Update cs.po #166
