### ISSUE TITLE
[Feature] List backgrounds download

### ISSUE THREAD

**Issue by alainm23** [calo001/fondo#17]
I would like to congratulate you, your application is incredible

I would like to be able to see my backgrounds already downloaded and play with them, it is a very long way to be entering settings and changing the background from the default application

**Comment by calo001** [comment]
Thanks for the comment. I have also thought about allowing to open the background folder, I already consider it a new feature for the following versions ;)

**Comment by calo001** [comment]
An option to download the wallpaper is now available in the 1.5.0 version! :D Enjoy!
