### ISSUE TITLE
Add quit shortcut key

### ISSUE THREAD

**Issue by eljefuri** [calo001/fondo#21]
Currently it seems to be necessary to use the mouse to quit Fondo. It would be nice if a common quit key were available. It seems that Ctrl+Q is the standard in Elementary, although [it is not universal](https://github.com/elementary/gala/issues/405) and perhaps at some point [something like this](https://github.com/elementary/switchboard-plug-keyboard/issues/69#issuecomment-338872844) gets implemented.

**Comment by eljefuri** [comment]
I just discovered that ESC quits the application, which is non-desirable for a lot of reasons (it was accidentally pressed and did not prompt me for any confirmation).

**Comment by calo001** [comment]
I am working on a next update, I plan to change the way to quit using the combination of Ctrl + Q ;)
