### ISSUE TITLE
Wallpaper not immediately applied: Elementary Juno.

### ISSUE THREAD

**Issue by CallieG** [calo001/fondo#22]
Hi, 

So, thanks for the wonderful app, but I have an issue.

It seems as though wallpapers are not immediately applied, rather, I must log out and back in for the change to occur.  

I did notice that the wallpaper is copied to ~/.local/share/backgrounds, rather than the equivalent in /usr/share/backgrounds.

Is this an elementary issue, then?

Or is it by design?

Would running Fondo with su creds change this?

**Comment by calo001** [comment]
It also happened to me with Loki when I used dual monitor. At the moment we can only hope that the elementary team finds a solution.

**Comment by AbhinavMadahar** [comment]
You can restart Gala without logging out:

```bash
killall -HUP gala
```
