### ISSUE TITLE
Download wallpaper to Pictures (or Downloads?) folder

### ISSUE THREAD

**Issue by cassidyjames** [calo001/fondo#23]
I'm a dork and like to set the same wallpaper on my computer and phone. It'd be awesome if I could set a wallpaper on my computer but also download it to somewhere easily accessible (like ~/Pictures or ~/Downloads) so I can throw it on my phone as well.

**Comment by calo001** [comment]
I could complement with this other issue [[Feature] List backgrounds download #17](https://github.com/calo001/fondo/issues/17) :smile:

**Comment by Theodin** [comment]
This would be a nice addition.
But I am partly happy after finding out that the wallpapers are saved to /.local/share/backgrounds.

**Comment by dquark** [comment]
All wallpapers are downloaded to the folder of application, in my case it's
`/home/pc/.var/app/com.github.calo001.fondo/data/backgrounds`
so until they add this feature, what you can do is create a link to this folder. Open up terminal go to home or whatever directory you want and type:
`ln -s /home/<name of your user>/.var/app/com.github.calo001.fondo/data/backgrounds <name of the folder, for example "wallpapers">`
example:
`ln -s /home/pc/.var/app/com.github.calo001.fondo/data/backgrounds wallpapers`

**Comment by calo001** [comment]
An option to download a photo is now available in the 1.5.0 version! :D Enjoy!
