### ISSUE TITLE
Copy link to wallpaper

### ISSUE THREAD

**Issue by cassidyjames** [calo001/fondo#24]
It'd be nice to be able to easily copy a link to the wallpaper that I can share with others if I find a cool wallpaper.

**Comment by calo001** [comment]
Thanks, I think it's an excellent idea, it also helps the community of unsplash photographers to publicize their work. I could take a little inspiration from the share button of the AppCenter, could you share an code example used in the AppCenter? Please :smiley:

**Comment by cassidyjames** [comment]
The share popover is at https://github.com/elementary/appcenter/blob/master/src/Widgets/SharePopover.vala
