### ISSUE TITLE
App deleting random files when a new wallpaper is apply

### ISSUE THREAD

**Issue by btd1337** [calo001/fondo#27]
Error when a new wallpaper is apply:

`Error removing file /home/arch/.thumbnails: Directory not empty`

Why to delete this folder?

![captura de tela de 2018-12-08 19-02-49](https://user-images.githubusercontent.com/11943860/49690667-ec2f1f00-fb1b-11e8-8b5d-e39147eb1aa0.png)

**Comment by isantop** [comment]
I'm getting a similar issue; the app tried to delete `$HOME/.ssh`, which is very not good. 

![screenshot from 2018-12-13 15-32-37](https://user-images.githubusercontent.com/5883565/49971704-94fac700-feec-11e8-998b-8dee4906f823.png)

It also appears to be deleting my `.bashrc` file

**Comment by calo001** [comment]
@isantop Are you using Fondo in elementary OS? That behavior is so weird :confused: 
I have an idea of where the error may be generating, I need to review my code.

**Comment by bilelmoussaoui** [comment]
It's due to this 
https://github.com/calo001/fondo/blob/143ce4e282281d0884726eb4309ce8427a01cdf5/src/utils/Wallpaper.vala#L197
The `XDG_GREETER_DATA_DIR` is not a common env variable. It's only there if the user uses Greeter. You should make sure that this env variable does exists first before removing anything :/ 
There must be a better way to handle greeter wallpaper other than having to remove stuff. It can cause issues to the user (see the comments on this issue)

**Comment by bilelmoussaoui** [comment]
Well, that code works on elementary because they are making sure that env variable do exists. Which is not the case with your application (it can be used on other DE that doesn't use Greeter)

**Comment by bilelmoussaoui** [comment]
You can just check if the env variable exists or not

**Comment by btd1337** [comment]
Does this command help anything?

`ls -1 /usr/share/xgreeters`

**Comment by calo001** [comment]
@bilelmoussaoui I push a new commit in master that uses a validator in the variable in the following way.
https://github.com/calo001/fondo/blob/6b286ef647fe331b2ee94ccf8e7b1441b89c2fd8/src/utils/Wallpaper.vala#L193-L237
I can not check if that is enough, Could you help me to check it @btd1337 please :pray: ?

**Comment by btd1337** [comment]
I confess to you that I am afraid of what can be erased if I take this test.

**Comment by calo001** [comment]
@btd1337 Don't worry, I'll try a VM instead.
