### ISSUE TITLE
Appdata file is not valid

### ISSUE THREAD

**Issue by bilelmoussaoui** [calo001/fondo#29]
You can run `appstream-util validate com.github.calo001.fondo.appdata.xml` to check if the file is correct.
```
com.github.calo001.fondo:          AppData problem: tag-invalid : <release> versions are not in order [1.0.0 before 1.0.1]
com.github.calo001.fondo:          AppData problem: tag-invalid : <release> versions are not in order [1.0.1 before 1.1.2]
com.github.calo001.fondo:          AppData problem: tag-invalid : <release> versions are not in order [1.1.2 before 1.1.3]
com.github.calo001.fondo:          AppData problem: tag-invalid : <release> versions are not in order [1.1.3 before 1.1.4]
Error loading AppData file: AppData file /app/share/appdata/com.github.calo001.fondo.appdata.xml was not valid
```

**Comment by bilelmoussaoui** [comment]
@calo001 This needs to be fixed on master before I can push any work on Flatpak here. Also the issue related to removing files :/

**Comment by calo001** [comment]
@bilelmoussaoui I already fix the errors of **<release> versions are not in order** in app data file and also the bug to delete files has a validation that check if the environment variable exist.

**Comment by calo001** [comment]
@bilelmoussaoui I check in dconf Editor that "org.gnome.desktop.background" change the path, often it is an elementary bud that changes the background until the session restarts.

**Comment by bilelmoussaoui** [comment]
What I mean is that no wallpaper is loaded by the application. I'm getting this on the terminal
```
(com.github.calo001.fondo:2): Json-CRITICAL **: 19:35:39.945: json_node_get_array: assertion 'JSON_NODE_IS_VALID (node)' failed

(com.github.calo001.fondo:2): Json-CRITICAL **: 19:35:39.945: json_array_get_elements: assertion 'array != NULL' failed
```
It seems that the app fails to get any wallpaper at all.

**Comment by calo001** [comment]
Is there a way I can prove it as a flatpak package? I think it could be some permissions error :confused: 
Since Meson build works well right?

**Comment by bilelmoussaoui** [comment]
You need to save the manifest as `com.github.calo001.fondo`
```
{
    "app-id": "com.github.calo001.fondo",
 	"base": "io.elementary.BaseApp",
 	"base-version": "juno",
    "runtime": "org.freedesktop.Platform",
    "sdk": "org.freedesktop.Sdk",
    "runtime-version": "18.08",
    "command": "com.github.calo001.fondo",
    "finish-args": [
        /* X11 + XShm */
        "--share=ipc", "--socket=x11",
        /* Wayland */
        "--socket=wayland",
        /* Network */
        "--share=network",
        /* dconf */
        "--filesystem=xdg-run/dconf", "--filesystem=~/.config/dconf:ro",
        "--talk-name=ca.desrt.dconf", "--env=DCONF_USER_CONFIG_DIR=.config/dconf"
    ],
    "modules": [
        {
            "name": "fondo",
            "buildsystem": "meson",
            "config-opts": ["--buildtype=release"],
            "sources":[
               {
                   "type": "git",
                   "url": "https://github.com/calo001/fondo.git"
               }
            ]
        }
    ]

}
```
You will need the io.elementary.BaseApp//juno. You can install it from flathub using
```
flatpak install flathub io.elementary.BaseApp//juno -y
```
Then you build & install the flatpak app using
```
flatpak-builder --install fondo com.github.calo001.fondo.json --force-clean
``` 

You can run the app later using `flatpak run com.github.calo001.fondo`

**Comment by bilelmoussaoui** [comment]
You should use libsoup and Glib.NetworkMonitor

**Comment by calo001** [comment]
I already found how to correct to make the request, we must add the property (libsoup) session.ssl_strict = false; and works!, I have a Status Code 200 and JSON object correctly, however now it does not allow me to see any image or download. I'll check for permission in manifest to add

**Comment by bilelmoussaoui** [comment]
Where do you store the cached images?

**Comment by calo001** [comment]
I have been researching and it seems that the Glib.File class does not have enough permissions to write files with the current configuration, I try with the permissions "--talk-name = org.gtk.vfs", "--talk-name = org .gtk.vfs. * "in the manifest but it has not worked.

**Comment by calo001** [comment]
It worked for me with the following configuration.

https://github.com/calo001/com.github.calo001.fondo/blob/master/com.github.calo001.fondo

**Comment by bilelmoussaoui** [comment]
The ssl_strict patch doesn't fix it here for me. I'm getting a 200 status code, but still the json is empty. You should handle that error case without having the app showing nothing like in this case.

**Comment by calo001** [comment]
@bilelmoussaoui I just added a check for the Status code, I installed it via flatpak on Ubuntu 18.10 and Manjaro Linux, it worked well for me, and I added the search feature :smile: Could you check if it already works well with you?

**Comment by bilelmoussaoui** [comment]
Will take a look asap :+1:
