### ISSUE TITLE
focus search

### ISSUE THREAD

**Issue by bodtx** [calo001/fondo#37]
Hi, when app start, can you focus the search field directly?
And better add a shortcut for seraching like ctrl+F or whatever

**Comment by calo001** [comment]
![search shortcut](https://user-images.githubusercontent.com/9545757/59141267-2d8b7480-896f-11e9-89ea-95f85a6e22af.png)

I want to show the unsplash credits as much as possible, so default focus on search entry will not be implementing, but a shortcut yes!!!

**Comment by bodtx** [comment]
Good idea, give a Ctrl + F to your people, my lord  👑
