### ISSUE TITLE
Mode Switch makes compilation fails

### ISSUE THREAD

**Issue by sudo-give-me-coffee** [calo001/fondo#42]
Error Log:

```
../src/widgets/HeaderBar.vala:56.35-56.52: error: The name `ModeSwitch' does not exist in the context of `Granite'
            var mode_switch = new Granite.ModeSwitch.from_icon_name ("display-brightness-symbolic", "weather-clear-night-symbolic");
                                  ^^^^^^^^^^^^^^^^^^
../src/widgets/HeaderBar.vala:56.17-56.131: error: var declaration not allowed with non-typed initializer
            var mode_switch = new Granite.ModeSwitch.from_icon_name ("display-brightness-symbolic", "weather-clear-night-symbolic");
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/widgets/HeaderBar.vala:57.13-57.23: error: The name `mode_switch' does not exist in the context of `App.Widgets.HeaderBar.new'
            mode_switch.primary_icon_tooltip_text = S.LIGHT_BACKGROUND;
            ^^^^^^^^^^^
../src/widgets/HeaderBar.vala:58.13-58.23: error: The name `mode_switch' does not exist in the context of `App.Widgets.HeaderBar.new'
            mode_switch.secondary_icon_tooltip_text = S.DARK_BACKGROUND;
            ^^^^^^^^^^^
../src/widgets/HeaderBar.vala:59.13-59.23: error: The name `mode_switch' does not exist in the context of `App.Widgets.HeaderBar.new'
            mode_switch.valign = Gtk.Align.CENTER;
            ^^^^^^^^^^^
../src/widgets/HeaderBar.vala:60.13-60.23: error: The name `mode_switch' does not exist in the context of `App.Widgets.HeaderBar.new'
            mode_switch.bind_property ("active", gtk_settings, "gtk_application_prefer_dark_theme");
            ^^^^^^^^^^^
../src/widgets/HeaderBar.vala:63.13-63.23: error: The name `mode_switch' does not exist in the context of `App.Widgets.HeaderBar.new'
            mode_switch.notify["active"].connect (() => {
            ^^^^^^^^^^^
../src/widgets/HeaderBar.vala:67.62-67.72: error: The name `mode_switch' does not exist in the context of `App.Widgets.HeaderBar.new'
            App.Application.settings.bind ("use-dark-theme", mode_switch, "active", GLib.SettingsBindFlags.DEFAULT);
                                                             ^^^^^^^^^^^
../src/widgets/HeaderBar.vala:130.28-130.38: error: The name `mode_switch' does not exist in the context of `App.Widgets.HeaderBar.new'
            this.pack_end (mode_switch);
```

File affected: /src/widgets/HeaderBar.vala

Lines: 56 a 67 and 130

**Comment by sudo-give-me-coffee** [comment]
This is because `"ModeSwitch"` was introduced in `libgranite` **5.2.3**, sorry

**Comment by lidianjin** [comment]
so, how can I to solve the problem, please..
here is my problem: 
`
root@lidianjin-Inspiron-3559:/home/lidianjin/fondo/fondo# ./app install-deps && ./app install
All dependencies are installed
The Meson build system
Version: 0.45.1
Source dir: /home/lidianjin/fondo/fondo
Build dir: /home/lidianjin/fondo/fondo/build
Build type: native build
Project name: com.github.calo001.fondo
Native C compiler: cc (gcc 7.4.0 "cc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0")
Native Vala compiler: valac (valac 0.40.8)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency glib-2.0 found: YES 2.56.4
Configuring config.h using configuration
Native dependency gobject-2.0 found: YES 2.56.4
Native dependency glib-2.0 found: YES 2.56.4
Native dependency granite found: YES 0.5
Native dependency gtk+-3.0 found: YES 3.22.30
Native dependency json-glib-1.0 found: YES 1.4.2
Native dependency libsoup-2.4 found: YES 2.62.1
Library posix found: YES
Program meson/post_install.py found: YES (/home/lidianjin/fondo/fondo/meson/post_install.py)
Build targets in project: 8
Found ninja-1.8.2 at /usr/bin/ninja
[1/41] Generating as-resources_h with a custom command.
XMLLINT not set and xmllint not found in path; skipping xml preprocessing.
[2/41] Generating as-resources_c with a custom command.
XMLLINT not set and xmllint not found in path; skipping xml preprocessing.
[5/41] Compiling Vala source ../src/configs/Constants.vala ../src/configs...c/Main.vala ../src/windows/PreviewWindow.vala ../src/windows/Window.vala.
FAILED: com.github.calo001.fondo@exe/src/configs/Constants.c com.github.calo001.fondo@exe/src/configs/Settings.c com.github.calo001.fondo@exe/src/configs/Strings.c com.github.calo001.fondo@exe/src/controllers/AppController.c com.github.calo001.fondo@exe/src/views/PhotosView.c com.github.calo001.fondo@exe/src/views/AppViewError.c com.github.calo001.fondo@exe/src/views/CardPhotoView.c com.github.calo001.fondo@exe/src/views/ButtonCategory.c com.github.calo001.fondo@exe/src/views/CategoriesView.c com.github.calo001.fondo@exe/src/views/EmptyHistoryView.c com.github.calo001.fondo@exe/src/views/EmptyView.c com.github.calo001.fondo@exe/src/views/LoadingView.c com.github.calo001.fondo@exe/src/views/FilterOptionsView.c com.github.calo001.fondo@exe/src/popovers/MenuPopover.c com.github.calo001.fondo@exe/src/popovers/WallpaperPopover.c com.github.calo001.fondo@exe/src/popovers/SharePopover.c com.github.calo001.fondo@exe/src/popovers/PhotoDetailPopover.c com.github.calo001.fondo@exe/src/models/Photo.c com.github.calo001.fondo@exe/src/models/SearchResult.c com.github.calo001.fondo@exe/src/utils/Wallpaper.c com.github.calo001.fondo@exe/src/utils/Networking.c com.github.calo001.fondo@exe/src/utils/JsonManager.c com.github.calo001.fondo@exe/src/utils/SchemaManager.c com.github.calo001.fondo@exe/src/widgets/BottonNavbar.c com.github.calo001.fondo@exe/src/widgets/ButtonTab.c com.github.calo001.fondo@exe/src/widgets/HeaderBar.c com.github.calo001.fondo@exe/src/widgets/LabelTop.c com.github.calo001.fondo@exe/src/widgets/LabelTotalResults.c com.github.calo001.fondo@exe/src/services/Connection.c com.github.calo001.fondo@exe/src/enums/Navigation.c com.github.calo001.fondo@exe/src/Application.c com.github.calo001.fondo@exe/src/Main.c com.github.calo001.fondo@exe/src/windows/PreviewWindow.c com.github.calo001.fondo@exe/src/windows/Window.c 
valac -C --debug --pkg posix --pkg libsoup-2.4 --pkg json-glib-1.0 --pkg gtk+-3.0 --pkg granite --pkg glib-2.0 --pkg gobject-2.0 --color=always --directory com.github.calo001.fondo@exe --basedir ../ --gresources=../data/com.github.calo001.fondo.gresource.xml ../src/configs/Constants.vala ../src/configs/Settings.vala ../src/configs/Strings.vala ../src/controllers/AppController.vala ../src/views/PhotosView.vala ../src/views/AppViewError.vala ../src/views/CardPhotoView.vala ../src/views/ButtonCategory.vala ../src/views/CategoriesView.vala ../src/views/EmptyHistoryView.vala ../src/views/EmptyView.vala ../src/views/LoadingView.vala ../src/views/FilterOptionsView.vala ../src/popovers/MenuPopover.vala ../src/popovers/WallpaperPopover.vala ../src/popovers/SharePopover.vala ../src/popovers/PhotoDetailPopover.vala ../src/models/Photo.vala ../src/models/SearchResult.vala ../src/utils/Wallpaper.vala ../src/utils/Networking.vala ../src/utils/JsonManager.vala ../src/utils/SchemaManager.vala ../src/widgets/BottonNavbar.vala ../src/widgets/ButtonTab.vala ../src/widgets/HeaderBar.vala ../src/widgets/LabelTop.vala ../src/widgets/LabelTotalResults.vala ../src/services/Connection.vala ../src/enums/Navigation.vala ../src/Application.vala ../src/Main.vala ../src/windows/PreviewWindow.vala ../src/windows/Window.vala
../src/widgets/HeaderBar.vala:54.35-54.52: error: The name `ModeSwitch' does not exist in the context of `Granite'
            var mode_switch = new Granite.ModeSwitch.from_icon_name ("display-brightness-symbolic", "weather-clear-night-symbolic");
                                  ^^^^^^^^^^^^^^^^^^
../src/widgets/HeaderBar.vala:54.17-54.131: error: var declaration not allowed with non-typed initializer
            var mode_switch = new Granite.ModeSwitch.from_icon_name ("display-brightness-symbolic", "weather-clear-night-symbolic");
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/widgets/HeaderBar.vala:55.13-55.23: error: The name `mode_switch' does not exist in the context of `App.Widgets.HeaderBar.new'
            mode_switch.primary_icon_tooltip_text = S.LIGHT_BACKGROUND;
            ^^^^^^^^^^^
../src/widgets/HeaderBar.vala:56.13-56.23: error: The name `mode_switch' does not exist in the context of `App.Widgets.HeaderBar.new'
            mode_switch.secondary_icon_tooltip_text = S.DARK_BACKGROUND;
            ^^^^^^^^^^^
../src/widgets/HeaderBar.vala:57.13-57.23: error: The name `mode_switch' does not exist in the context of `App.Widgets.HeaderBar.new'
            mode_switch.valign = Gtk.Align.CENTER;
            ^^^^^^^^^^^
../src/widgets/HeaderBar.vala:58.13-58.23: error: The name `mode_switch' does not exist in the context of `App.Widgets.HeaderBar.new'
            mode_switch.bind_property ("active", gtk_settings, "gtk_application_prefer_dark_theme");
            ^^^^^^^^^^^
../src/widgets/HeaderBar.vala:61.13-61.23: error: The name `mode_switch' does not exist in the context of `App.Widgets.HeaderBar.new'
            mode_switch.notify["active"].connect (() => {
            ^^^^^^^^^^^
../src/widgets/HeaderBar.vala:65.62-65.72: error: The name `mode_switch' does not exist in the context of `App.Widgets.HeaderBar.new'
            App.Application.settings.bind ("use-dark-theme", mode_switch, "active", GLib.SettingsBindFlags.DEFAULT);
                                                             ^^^^^^^^^^^
../src/widgets/HeaderBar.vala:76.37-76.64: error: The name `markup_accel_tooltip' does not exist in the context of `Granite'
            search.tooltip_markup = Granite.markup_accel_tooltip (
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/widgets/HeaderBar.vala:117.28-117.38: error: The name `mode_switch' does not exist in the context of `App.Widgets.HeaderBar.new'
            this.pack_end (mode_switch);
                           ^^^^^^^^^^^
../src/utils/Wallpaper.vala:177.13-177.40: error: The name `Application' does not exist in the context of `Granite.Services'
            Granite.Services.Application.set_progress_visible.begin (visible, (obj, res) => {
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/utils/Wallpaper.vala:164.13-164.40: error: The name `Application' does not exist in the context of `Granite.Services'
            Granite.Services.Application.set_progress.begin (progress, (obj, res) => {
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/windows/PreviewWindow.vala:95.40-95.67: error: The name `markup_accel_tooltip' does not exist in the context of `Granite'
            btn_close.tooltip_markup = Granite.markup_accel_tooltip (
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 13 error(s), 0 warning(s)
[6/41] Compiling C object 'com.github.calo001.fondo@exe/meson-generated_.._as-resources.c.o'.
ninja: build stopped: subcommand failed.
Unable to build project, please review log
`

**Comment by lidianjin** [comment]
so, how can I to solve the problem, please..
here is my problem:
```
root@lidianjin-Inspiron-3559:/home/lidianjin/fondo/fondo# ./app install-deps && ./app install
All dependencies are installed
The Meson build system
Version: 0.45.1
Source dir: /home/lidianjin/fondo/fondo
Build dir: /home/lidianjin/fondo/fondo/build
Build type: native build
Project name: com.github.calo001.fondo
Native C compiler: cc (gcc 7.4.0 "cc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0")
Native Vala compiler: valac (valac 0.40.8)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency glib-2.0 found: YES 2.56.4
Configuring config.h using configuration
Native dependency gobject-2.0 found: YES 2.56.4
Native dependency glib-2.0 found: YES 2.56.4
Native dependency granite found: YES 0.5
Native dependency gtk+-3.0 found: YES 3.22.30
Native dependency json-glib-1.0 found: YES 1.4.2
Native dependency libsoup-2.4 found: YES 2.62.1
Library posix found: YES
Program meson/post_install.py found: YES (/home/lidianjin/fondo/fondo/meson/post_install.py)
Build targets in project: 8
Found ninja-1.8.2 at /usr/bin/ninja
[1/41] Generating as-resources_h with a custom command.
XMLLINT not set and xmllint not found in path; skipping xml preprocessing.
[2/41] Generating as-resources_c with a custom command.
XMLLINT not set and xmllint not found in path; skipping xml preprocessing.
[5/41] Compiling Vala source ../src/configs/Constants.vala ../src/configs...c/Main.vala ../src/windows/PreviewWindow.vala ../src/windows/Window.vala.
FAILED: com.github.calo001.fondo@exe/src/configs/Constants.c com.github.calo001.fondo@exe/src/configs/Settings.c com.github.calo001.fondo@exe/src/configs/Strings.c com.github.calo001.fondo@exe/src/controllers/AppController.c com.github.calo001.fondo@exe/src/views/PhotosView.c com.github.calo001.fondo@exe/src/views/AppViewError.c com.github.calo001.fondo@exe/src/views/CardPhotoView.c com.github.calo001.fondo@exe/src/views/ButtonCategory.c com.github.calo001.fondo@exe/src/views/CategoriesView.c com.github.calo001.fondo@exe/src/views/EmptyHistoryView.c com.github.calo001.fondo@exe/src/views/EmptyView.c com.github.calo001.fondo@exe/src/views/LoadingView.c com.github.calo001.fondo@exe/src/views/FilterOptionsView.c com.github.calo001.fondo@exe/src/popovers/MenuPopover.c com.github.calo001.fondo@exe/src/popovers/WallpaperPopover.c com.github.calo001.fondo@exe/src/popovers/SharePopover.c com.github.calo001.fondo@exe/src/popovers/PhotoDetailPopover.c com.github.calo001.fondo@exe/src/models/Photo.c com.github.calo001.fondo@exe/src/models/SearchResult.c com.github.calo001.fondo@exe/src/utils/Wallpaper.c com.github.calo001.fondo@exe/src/utils/Networking.c com.github.calo001.fondo@exe/src/utils/JsonManager.c com.github.calo001.fondo@exe/src/utils/SchemaManager.c com.github.calo001.fondo@exe/src/widgets/BottonNavbar.c com.github.calo001.fondo@exe/src/widgets/ButtonTab.c com.github.calo001.fondo@exe/src/widgets/HeaderBar.c com.github.calo001.fondo@exe/src/widgets/LabelTop.c com.github.calo001.fondo@exe/src/widgets/LabelTotalResults.c com.github.calo001.fondo@exe/src/services/Connection.c com.github.calo001.fondo@exe/src/enums/Navigation.c com.github.calo001.fondo@exe/src/Application.c com.github.calo001.fondo@exe/src/Main.c com.github.calo001.fondo@exe/src/windows/PreviewWindow.c com.github.calo001.fondo@exe/src/windows/Window.c 
valac -C --debug --pkg posix --pkg libsoup-2.4 --pkg json-glib-1.0 --pkg gtk+-3.0 --pkg granite --pkg glib-2.0 --pkg gobject-2.0 --color=always --directory com.github.calo001.fondo@exe --basedir ../ --gresources=../data/com.github.calo001.fondo.gresource.xml ../src/configs/Constants.vala ../src/configs/Settings.vala ../src/configs/Strings.vala ../src/controllers/AppController.vala ../src/views/PhotosView.vala ../src/views/AppViewError.vala ../src/views/CardPhotoView.vala ../src/views/ButtonCategory.vala ../src/views/CategoriesView.vala ../src/views/EmptyHistoryView.vala ../src/views/EmptyView.vala ../src/views/LoadingView.vala ../src/views/FilterOptionsView.vala ../src/popovers/MenuPopover.vala ../src/popovers/WallpaperPopover.vala ../src/popovers/SharePopover.vala ../src/popovers/PhotoDetailPopover.vala ../src/models/Photo.vala ../src/models/SearchResult.vala ../src/utils/Wallpaper.vala ../src/utils/Networking.vala ../src/utils/JsonManager.vala ../src/utils/SchemaManager.vala ../src/widgets/BottonNavbar.vala ../src/widgets/ButtonTab.vala ../src/widgets/HeaderBar.vala ../src/widgets/LabelTop.vala ../src/widgets/LabelTotalResults.vala ../src/services/Connection.vala ../src/enums/Navigation.vala ../src/Application.vala ../src/Main.vala ../src/windows/PreviewWindow.vala ../src/windows/Window.vala
../src/widgets/HeaderBar.vala:54.35-54.52: error: The name `ModeSwitch' does not exist in the context of `Granite'
            var mode_switch = new Granite.ModeSwitch.from_icon_name ("display-brightness-symbolic", "weather-clear-night-symbolic");
                                  ^^^^^^^^^^^^^^^^^^
../src/widgets/HeaderBar.vala:54.17-54.131: error: var declaration not allowed with non-typed initializer
            var mode_switch = new Granite.ModeSwitch.from_icon_name ("display-brightness-symbolic", "weather-clear-night-symbolic");
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/widgets/HeaderBar.vala:55.13-55.23: error: The name `mode_switch' does not exist in the context of `App.Widgets.HeaderBar.new'
            mode_switch.primary_icon_tooltip_text = S.LIGHT_BACKGROUND;
            ^^^^^^^^^^^
../src/widgets/HeaderBar.vala:56.13-56.23: error: The name `mode_switch' does not exist in the context of `App.Widgets.HeaderBar.new'
            mode_switch.secondary_icon_tooltip_text = S.DARK_BACKGROUND;
            ^^^^^^^^^^^
../src/widgets/HeaderBar.vala:57.13-57.23: error: The name `mode_switch' does not exist in the context of `App.Widgets.HeaderBar.new'
            mode_switch.valign = Gtk.Align.CENTER;
            ^^^^^^^^^^^
../src/widgets/HeaderBar.vala:58.13-58.23: error: The name `mode_switch' does not exist in the context of `App.Widgets.HeaderBar.new'
            mode_switch.bind_property ("active", gtk_settings, "gtk_application_prefer_dark_theme");
            ^^^^^^^^^^^
../src/widgets/HeaderBar.vala:61.13-61.23: error: The name `mode_switch' does not exist in the context of `App.Widgets.HeaderBar.new'
            mode_switch.notify["active"].connect (() => {
            ^^^^^^^^^^^
../src/widgets/HeaderBar.vala:65.62-65.72: error: The name `mode_switch' does not exist in the context of `App.Widgets.HeaderBar.new'
            App.Application.settings.bind ("use-dark-theme", mode_switch, "active", GLib.SettingsBindFlags.DEFAULT);
                                                             ^^^^^^^^^^^
../src/widgets/HeaderBar.vala:76.37-76.64: error: The name `markup_accel_tooltip' does not exist in the context of `Granite'
            search.tooltip_markup = Granite.markup_accel_tooltip (
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/widgets/HeaderBar.vala:117.28-117.38: error: The name `mode_switch' does not exist in the context of `App.Widgets.HeaderBar.new'
            this.pack_end (mode_switch);
                           ^^^^^^^^^^^
../src/utils/Wallpaper.vala:177.13-177.40: error: The name `Application' does not exist in the context of `Granite.Services'
            Granite.Services.Application.set_progress_visible.begin (visible, (obj, res) => {
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/utils/Wallpaper.vala:164.13-164.40: error: The name `Application' does not exist in the context of `Granite.Services'
            Granite.Services.Application.set_progress.begin (progress, (obj, res) => {
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../src/windows/PreviewWindow.vala:95.40-95.67: error: The name `markup_accel_tooltip' does not exist in the context of `Granite'
            btn_close.tooltip_markup = Granite.markup_accel_tooltip (
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 13 error(s), 0 warning(s)
[6/41] Compiling C object 'com.github.calo001.fondo@exe/meson-generated_.._as-resources.c.o'.
ninja: build stopped: subcommand failed.
Unable to build project, please review log
```

**Comment by calo001** [comment]
@lidianjin Did you try to install the elementary SDK?

`sudo apt install elementary-sdk`

**Comment by lidianjin** [comment]
@calo001 Thank you so much. But I had installed fondo from [Flathub](https://flathub.org/) by [Flatpak](https://flatpak.org/setup/Ubuntu/). Oh, fondo is cool, thank you again.
