### ISSUE TITLE
Wont comple with new Vala 0.44.4

### ISSUE THREAD

**Issue by tim77** [calo001/fondo#48]
[build.log](https://github.com/calo001/fondo/files/3267833/build.log)

**Comment by tim77** [comment]
https://gitlab.gnome.org/GNOME/vala/issues/803#note_527338

**Comment by tim77** [comment]
@calo001 hope this [will fixed in 0.46](https://gitlab.gnome.org/GNOME/vala/milestones/14).

**Comment by calo001** [comment]
@tim77  Could you please continue reporting me and if necessary a change in the code? :pray:

**Comment by tim77** [comment]
Sure, happily.

**Comment by worldofpeace** [comment]
I've compiled fondo with vala 0.46.1 without problems on NixOS
* [build log](https://gist.github.com/worldofpeace/a851c283264508a992bbd282ab7f922e)

I believe this issue can be closed.

**Comment by tim77** [comment]
Yep, me too https://koji.fedoraproject.org/koji/buildinfo?buildID=1382500
