### ISSUE TITLE
Login screen does not use selected wallpaper

### ISSUE THREAD

**Issue by drom98** [calo001/fondo#51]
As the title says, the login background does not change when selecting a new image.

**Comment by eddiecsilva** [comment]
I also noticed this, I came here to open a report and I saw that it has already been reported.

**Comment by calo001** [comment]
I am already reviewing :eyes:  what may be the reason for this problem :thinking:  thanks for reporting the bug.

**Comment by calo001** [comment]
Fondo 1.3.2 fix this issue!! :smile:
