### ISSUE TITLE
Porting a Fondo to MacOS

### ISSUE THREAD

**Issue by aimproxy** [calo001/fondo#56]
Hi, if you have a mac, thats would be a great app for it, please consider porting this GTK+ app to macOS.

I found something on [stackoverflow](https://stackoverflow.com/questions/10230557/porting-a-gtk-app-to-mac-osx) !

**Comment by calo001** [comment]
@aimproxy Hey! I have planned to bring Fondo to other platforms, but using their native tools and languages :+1: 

PD: An android version is currently on development
