### ISSUE TITLE
How to test the created translation?

### ISSUE THREAD

**Issue by Etamuk** [calo001/fondo#57]
Hello,

first thank you for this great app. It makes it easy searching for beautiful wallpapers.
I like your app and so I translated it into german language (my native language). 
Is there an easy way to test the translation before creating a pull request? 
Thank you.
Best regards

**Comment by calo001** [comment]
Hey, thanks! @Etamuk I really appreciate your support!! :+1: 

Unfortunately, I don't know an easy way to check the translate, but, you can make the pull request so I can do a review :smile:

**Comment by Etamuk** [comment]
Thank you for your quick answer @calo001 
I will do a proofreading tomorrow and after that i will send a PR.
I give my very best with translating :smile: 
Best regards from Germany :hand:

**Comment by calo001** [comment]
Awesome, @Etamuk Thanks, friend!!! :+1:
