### ISSUE TITLE
No way to set the lock screen background

### ISSUE THREAD

**Issue by thekad** [calo001/fondo#63]
In gnome 3, two different settings for regular background and lock-screen background exist. Fondo only changes the regular background, and as the downloaded image is somewhere not in the Pictures folder, is not easy to set it as the lock screen background. It would be nice if Fondo was able to do one or the other or both.

**Comment by calo001** [comment]
Fondo should change the lock screen in gnome, but let me give a check, though I'm planning to feature the possibility of using a different photo for wallpaper and look screen.
