### ISSUE TITLE
Image license and surce - what can we do with it

### ISSUE THREAD

**Issue by ieugen** [calo001/fondo#67]
Hello, 

What is the license and the source or the images? How can we use them. 
It would be great to have the answer to this information should be added to the project. 

Regards,
Eugen

**Comment by azazello4** [comment]
[https://unsplash.com/license](https://unsplash.com/license)

**Comment by ieugen** [comment]
Thanks, That is awesome. I did not know about unsplash.

**Comment by calo001** [comment]
@ieugen, Of course, would be a good idea to provide that information in the project, I need to design the best way to do that and I'll let you know :+1:
