### ISSUE TITLE
No previews availible 

### ISSUE THREAD

**Issue by Etamuk** [calo001/fondo#68]
Hello calo,

since some weeks Fondo doesn't load the preview pictures. 
When I click on an empty preview Fondo tells me "Error copy from URl to directory".
After confirming the message the wallpaper changes to black.
Please see also my screenshot.
___
I am using Ubuntu 19.04 with Gnome Shell 3.32.1
Installed Fondo as flatpak-app, version 1.3.4 installed 

![Bildschirmfoto von 2019-10-10 20-46-43](https://user-images.githubusercontent.com/20098065/66597942-3fd92180-eba0-11e9-812a-8f600ac5ffd7.png)

**Comment by calo001** [comment]
This issue should be fixed now :smile:

**Comment by Etamuk** [comment]
Oh yeah! That's fine and it's working :smile:
