### ISSUE TITLE
Not found on AppCenter

### ISSUE THREAD

**Issue by pablopunk** [calo001/fondo#7]
When I click the link to download via AppCenter this screen appears:

![screenshot from 2018-09-10 17-10-17](https://user-images.githubusercontent.com/4324982/45306268-8b904600-b51c-11e8-8634-6aaafa735502.png)

**Comment by calo001** [comment]
Fondo is only available in Juno beta, maybe you are using Loki, and therefore not appear in the AppCenter. Soon I wil try to make it available in Loki :)

**Comment by pablopunk** [comment]
@calo001 aha! That's it. I am using loki, sorry I didn't get that was only for Juno. Thanks for the quick response tho. The app looks awesome.

**Comment by calo001** [comment]
Thanks for your comment :smiley:
