### ISSUE TITLE
Delete photos from history

### ISSUE THREAD

**Issue by j718** [calo001/fondo#73]
It would be nice to be able to delete photos from history to keep only favorites. It may also be good to have a favorites section.

**Comment by 4jNsY6fCVqZv** [comment]
The possibility to delete would be the minimum. It would be wonderful if Fondo could also respect the global privacy settings in elementary OS. What do you think?

**Comment by calo001** [comment]
@4jNsY6fCVqZv I really like your idea, I'm sure the delete feature is part of my early plans and respecting the global privacy would be a great integration, thanks :+1:

**Comment by 4jNsY6fCVqZv** [comment]
@calo001 Thanks for your feedback! Should I create a separate issue for it or is it hereby added to your roadmap?

**Comment by calo001** [comment]
@4jNsY6fCVqZv A separate issue would be awesome please 🙏

**Comment by calo001** [comment]
The history finally has the option of deleting an item in the 1.3.9 version!

**Comment by 4jNsY6fCVqZv** [comment]
@calo001 Does this mean it will be possible to delete the history manually or does this correlate with the history settings in the Security & Privacy tab of Switchboard as well?

**Comment by calo001** [comment]
Hi, @4jNsY6fCVqZv This update only allows delete a photo by clicking in the trash icon, I'm making small updates, so respecting the Privacy settings it's a pending feature yet. :smile: 

![image](https://user-images.githubusercontent.com/9545757/82756733-8c751400-9da1-11ea-99a7-dcff72626814.png)

**Comment by 4jNsY6fCVqZv** [comment]
Thank you! I just discovered again that we made two issues out of it. :smile:
