### ISSUE TITLE
[Feature] Other sources

### ISSUE THREAD

**Issue by eliocamp** [calo001/fondo#79]
I'm not so keen on photographs as wallpaper so I rarely use any background from Fondo. Nevertheless, I keep the app installed just because how beautiful and slick it is. With that as a background, would you entertain the idea of adding more sources of pictures? I'm thinking mostly about [Wallhaven](https://wallhaven.cc/), which is my website of choice because it's got a ton of illustrations (it's also got a hefty proportion of NSW content, which you can thankfully filter out). This website in particular has [an API](https://wallhaven.cc/help/api). 

I would understand if adding more sources is out of scope, but I wanted to ask anyway. Thanks for the lovely app.

**Comment by calo001** [comment]
@eliocamp Hey thanks for having installed Fondo :+1: It would be awesome if you can give a try to use some photos! I currently have decided to use only Unsplash photos and improve the user experience with it as I can. I think to create another app to use a different API would be a more consistent decision. For the moment I don't have plans to do it, but It would be very interesting in the future.
