### ISSUE TITLE
couldn't build on ubuntu 18.04 bionic

### ISSUE THREAD

**Issue by mmohammadi9812** [calo001/fondo#94]
I cloned the repo, ran ```./app install-deps``` and then ```./app run``` and ```./app install``` but both of them failed.
I removed the folder once and cloned it again, ```./app install-deps``` says all dependencies are met, but the result of ```./app install``` is same and fails: https://pastebin.com/RfTAeD4i

**Comment by calo001** [comment]
@mmohammadi9812 Hi, please install the elementary development library:
sudo apt install elementary-sdk
:+1:

**Comment by mmohammadi9812** [comment]
I couldn't run ```sudo apt install elementry-sdk``` and finding its repo and installing it was not easy, but I installed it from flathub, so I'm gonna close this.
