### ISSUE TITLE
Wallpaper does not extend on whole workspace when in multitasking view

### ISSUE THREAD

**Issue by dntzbgh** [calo001/fondo#95]
When I press windows key + down ( or s key) on elementary to show me the multitask view, the wallpaper set by fondo does not fit the entire workspace. I will attach an image so that you can understand better what I mean.
![photo6035310846776815878](https://user-images.githubusercontent.com/47480841/77256740-c37f5a00-6c78-11ea-841c-60331b9b0590.jpg)
![photo6035310846776815879](https://user-images.githubusercontent.com/47480841/77256744-c4b08700-6c78-11ea-8e88-63fdb9b5ea67.jpg)

**Comment by calo001** [comment]
@dntzbgh Thanks for reporting this bug :+1:  does this only happening with Fondo's wallpapers? otherwise, this could be a Gala issue :thinking:

**Comment by dntzbgh** [comment]
I had a bug happening with a default wallpaper too, but I don't know what could have caused it since now seems it works as it should be. But a Gala thing for sure.
